# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- powershell: |
    $deploymentrecordcount = 5
    Write-Output ("##vso[task.setvariable variable=deploymentrecordcount;isOutput=true]$deploymentrecordcount")
    Write-Host "Set deploymentrecordcount to $deploymentrecordcount"
  displayName: 'Set Deployment Record Count'
  name: 'count'

- powershell: |
    $deploymentrecordcount = $env:deploymentrecordcount
    Write-Host "Deployment Record Count in subsequent task: $deploymentrecordcount"
    echo $(count)
  displayName: 'Use Deployment Record Count'